-- Jalankan sekali di Supabase SQL Editor.
-- Aman dijalankan ulang; data yang sudah ada tidak dihapus.

create table if not exists public.lab_rooms (
  id bigint generated by default as identity primary key,
  room_name text not null unique
);

insert into public.lab_rooms (room_name)
select 'Lab C.413' where not exists (select 1 from public.lab_rooms where room_name = 'Lab C.413');
insert into public.lab_rooms (room_name)
select 'Lab C.405' where not exists (select 1 from public.lab_rooms where room_name = 'Lab C.405');

create table if not exists public.lab_schedules (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.lab_rooms(id) on delete restrict,
  day_name text not null,
  start_time time not null,
  end_time time not null,
  subject text not null,
  class_name text,
  lecturer_name text,
  schedule_type text not null default 'kuliah',
  status text not null default 'active',
  semester_label text not null default 'Belum ditentukan',
  period_type text not null default 'gasal',
  period_start date not null default current_date,
  period_end date not null default current_date,
  participant_count integer not null default 0,
  participant_nims text[] not null default '{}',
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.lab_bookings (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.lab_rooms(id) on delete restrict,
  booking_date date not null,
  day_name text not null,
  start_time time not null,
  end_time time not null,
  borrower_name text not null,
  borrower_role text not null,
  borrower_contact text not null,
  purpose text not null,
  status text not null default 'pending',
  admin_note text,
  booking_code text not null unique,
  booking_category text not null default 'perkuliahan',
  class_name text,
  participant_count integer not null default 1,
  participant_nims text[] not null default '{}',
  rules_accepted_at timestamptz,
  academic_year text not null default 'Belum ditentukan',
  academic_period text not null default 'di_luar_periode',
  created_at timestamptz not null default now()
);

alter table public.lab_schedules
  add column if not exists semester_label text not null default 'Belum ditentukan',
  add column if not exists period_type text not null default 'gasal',
  add column if not exists period_start date not null default current_date,
  add column if not exists period_end date not null default current_date,
  add column if not exists archived_at timestamptz;

create index if not exists lab_schedules_room_day_idx
  on public.lab_schedules (room_id, day_name, start_time);
create index if not exists lab_bookings_room_date_idx
  on public.lab_bookings (room_id, booking_date, start_time);
create index if not exists lab_bookings_status_idx
  on public.lab_bookings (status, booking_date);

drop view if exists public.lab_schedule_view;
create view public.lab_schedule_view as
select
  s.id,
  r.room_name,
  s.day_name,
  s.start_time,
  s.end_time,
  s.subject,
  s.class_name,
  s.lecturer_name,
  s.schedule_type,
  s.semester_label,
  s.period_type,
  s.period_start,
  s.period_end,
  s.status
from public.lab_schedules s
join public.lab_rooms r on r.id = s.room_id
where s.status = 'active'
  and s.period_start is not null
  and s.period_end is not null
  and s.period_end >= s.period_start;

drop view if exists public.lab_booking_view;
create view public.lab_booking_view with (security_invoker = true) as
select
  b.id,
  b.room_id,
  r.room_name,
  b.booking_date,
  b.day_name,
  b.start_time,
  b.end_time,
  b.borrower_name,
  b.borrower_role,
  b.borrower_contact,
  b.purpose,
  b.status,
  b.admin_note,
  b.created_at,
  b.booking_code,
  b.booking_category,
  b.class_name,
  b.participant_count,
  b.participant_nims,
  b.rules_accepted_at,
  b.academic_year,
  b.academic_period
from public.lab_bookings b
join public.lab_rooms r on r.id = b.room_id;

-- Browser tidak mengakses tabel secara langsung. Semua akses melewati function
-- dengan service-role key, sehingga data booking tidak terbuka melalui anon key.
alter table public.lab_rooms enable row level security;
alter table public.lab_schedules enable row level security;
alter table public.lab_bookings enable row level security;

revoke all on public.lab_rooms from anon, authenticated;
revoke all on public.lab_schedules from anon, authenticated;
revoke all on public.lab_bookings from anon, authenticated;
revoke all on public.lab_schedule_view from anon, authenticated;
revoke all on public.lab_booking_view from anon, authenticated;
