-- Jalankan sekali di Supabase SQL Editor proyek baru.
create table if not exists public.lab_software (
  id bigint generated by default as identity primary key,
  software_name text not null,
  version text,
  license_type text not null default 'Tidak dicantumkan',
  license_status text not null default 'lifetime' check (license_status in ('lifetime','expires')),
  expires_on date,
  room_id bigint references public.lab_rooms(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lab_software_expiry_check check (
    (license_status = 'lifetime' and expires_on is null) or
    (license_status = 'expires' and expires_on is not null)
  )
);
create index if not exists lab_software_room_idx on public.lab_software(room_id);
alter table public.lab_software enable row level security;
